[mysql]                         # 使用するRDBMS
    dbName     = "tabecolla"    # データベース名
    host       = "commandservice_db"   # ホスト名
    port       = 3306           # ポート番号
    user       = "root"         # ユーザー名
    pass       = "p@ssw0rd"     # パスワード
    testDbName = "tabecolla_test"    # データベース名
    testHost   = "commandservice_db"   # ホスト名
    testPort   = 3306           # ポート番号
    testUser   = "root"         # ユーザー名
    testPass   = "p@ssw0rd"     # パスワード
    sslMode    = "false"        # SSLモード
    whitelist  = [              # アクセスするデータベースオブジェクト
        "login_users",          # userテーブル
        "stores",               # storeテーブル
        "store_categories"      # store_categoryテーブル
    ]